name: "Test"

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install cocotb requirements
      run: |
        python3 -m pip install -r test/requirements.txt

    - name: Run cocotb simulation
      run: |
        cd test
        make





